console.log('Hello, webpack!');
/*
import id from '../sub'
import password from '../sub'
import submit from '../sub'
import autofocus from '../sub'
import idmsg from '../sub'
import pwmsg from '../sub'
import ID_REGEX from '../sub'
import PW_REGEX from '../sub'
import ID_ERROR_MSG from '../sub'
import PW_ERROR_MSG from '../sub'
import checkIdValidation from '../sub'
import Idfocusout from '../sub'
import Pwfocusout from '../sub'
import checkPasswordValidation from '../sub'
import checkIdCheck from '../sub'
import checkPasswordCheck from '../sub'
import LoginSubmit from '../sub'
*/